name: 'Versioning web frontends'

on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
      - edited

env:
  NODE_VERSION: 18

jobs:
  bump:
    name: 'Bump Version'
    if: ${{ contains(github.event.comment.body, '!!books-frontend version') || contains(github.event.comment.body, '!!select-frontend version') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Determine Frontend'
        id: determine-frontend
        run: |
          if [[ ${{ contains(github.event.comment.body, '!!books-frontend version') }} == 'true' ]]; then
            echo "frontend=ridibooks" >> $GITHUB_OUTPUT
          elif [[ ${{ contains(github.event.comment.body, '!!select-frontend version') }} == 'true' ]]; then
            echo "frontend=select" >> $GITHUB_OUTPUT
          fi
      
      - name: 'Echo Github Env'
        env:
          ISSUE_COMMENT: ${{ github.event.comment.body }}
        working-directory: 'frontends/${{ steps.determine-frontend.outputs.frontend }}'
        run: |
          echo $(cat package.json | jq -r '.version')
          VERSION_TYPE=$(echo "$ISSUE_COMMENT" | sed 's/!!${{ steps.determine-frontend.outputs.frontend == 'ridibooks' && 'books-frontend' || 'select-frontend' }} version //')
          echo "$VERSION_TYPE"