name: 'Versioning web frontends'

on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
      - edited

env:
  NODE_VERSION: 18

jobs:
  bump:
    name: 'Bump Version'
    if: ${{ contains(github.event.comment.body, '!!books-frontend version') || contains(github.event.comment.body, '!!select-frontend version') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Determine Frontend'
        id: determine-frontend
        run: |
          if [[ ${{ contains(github.event.comment.body, '!!books-frontend version') }} == 'true' ]]; then
            echo "frontend=ridibooks" >> $GITHUB_OUTPUT
          elif [[ ${{ contains(github.event.comment.body, '!!select-frontend version') }} == 'true' ]]; then
            echo "frontend=select" >> $GITHUB_OUTPUT
          fi
      
      - name: 'Echo Github Env'
        working-directory: 'frontends/${{ steps.determine-frontend.outputs.frontend }}'
        run: |
          echo $(cat package.json | jq -r '.version')